### ISSUE TITLE
Add New Term Types

### ISSUE THREAD

**Issue by lnanderson** [biopragmatics/debio#3]
@cthoyt is it possible to add the following new term types (if in scope).

[Typedef]
id: debio:00000XX
name: has protection role
def: "Sibling relationship to vo:0000615 (vaccine role)"
created_by: orcid:0000-0002-8741-7823

[Typedef]
id: debio:00000XX
name: has mechanism of protection
def: "Sibling relationship to vo:0004909 (immunizes against disease process)"
created_by: orcid:0000-0002-8741-7823

[Typedef]
id: debio:00000XX
name: vaccine has immunogen
def: "connects a vaccine to any substance that generates an adaptive immune response upon exposure to a host organism"
created_by: orcid:0000-0002-8741-7823

**Comment by cthoyt** [comment]
Can you give a concrete example for each as well as an estimation of how often the relations will be used?

**Comment by lnanderson** [comment]
@cthoyt Here is an example combining all three. I think these relations would be used quite often.

curie: [vo:0004987](http://purl.obolibrary.org/obo/VO_0004987) (Comirnaty vaccine)
relation_id: debio:00000XX (has protection role)
object_id: [vo:0000857](http://purl.obolibrary.org/obo/VO_0000857) (vaccine-induced immune correlate of protection)

curie: [vo:0004987](http://purl.obolibrary.org/obo/VO_0004987) (Comirnaty vaccine)
relation_id: debio:00000XX (has mechanism of protection)
object_id: [vo:0000008](http://purl.obolibrary.org/obo/VO_0000008) (vaccine-induced lymphocyte activation)

curie: [vo:0004987](http://purl.obolibrary.org/obo/VO_0004987) (Comirnaty vaccine)
relation_id: debio:00000XX (vaccine has immunogen)
object_id: uniprot:[P0DTC2](https://purl.uniprot.org/uniprot/P0DTC2) (Spike glycoprotein)

**Comment by cthoyt** [comment]
I don't think the first one makes sense. If something has a role, use the RO:has role relation. The object in the example isn't a role, it's a process. 

What's the range for "has mechanism of protection"? any BFO process? or ideally something more specific?

I commented on GitLab about the third one, I gave an alternative that reuses existing modeling patterns from VO + GO annotations database

**Comment by lnanderson** [comment]
resolve via GitLab with @cthoyt.
